export const SKILLS_DATA = {
  frontend: [
    { name: "HTML5", level: 90, icon: "TbBrandHtml5" },
    { name: "CSS3", level: 80, icon: "TbBrandCss3" },
    { name: "Next.js", level: 75, icon: "SiNextdotjs" },
    { name: "TypeScript", level: 80, icon: "TbBrandTypescript" },
    { name: "JavaScript", level: 80, icon: "TbBrandJavascript" },
    { name: "Redux", level: 90, icon: "SiRedux" },
    { name: "React", level: 80, icon: "FaReact" },
  ],
  backend: [
    { name: "Node.js", level: 80, icon: "FaNodeJs" },
    { name: "Express.js", level: 80, icon: "SiExpress" },
    { name: "Rest APIs", level: 80, icon: "TbApi" },
    { name: "Django", level: 80, icon: "SiDjango" },
    { name: "Python", level: 90, icon: "FaPython" },
    { name: "MongoDB", level: 80, icon: "SiMongodb" },
    { name: "Docker", level: 70, icon: "SiDocker" },
  ],
  platforms: [
    { name: "VS Code", level: 80, icon: "TbBrandVscode" },
    { name: "Jupyter Notebook", level: 80, icon: "SiJupyter" },
    { name: "Google Colab", level: 80, icon: "SiGooglecolab" },
    { name: "PyCharm", level: 70, icon: "SiPycharm" },
    { name: "GitHub", level: 70, icon: "SiGithub" },
    { name: "Postman", level: 70, icon: "SiPostman" },
    { name: "Kaggle", level: 70, icon: "SiKaggle" },
  ],
  Other: [
    { name: "Pandas", level: 80, icon: "SiPandas" },
    { name: "Matplotlib", level: 80, icon: "SiPlotly" },
    { name: "Seaborn", level: 80, icon: "TbGraph" },
    { name: "Git", level: 70, icon: "SiGit" },
    { name: "Tailwind CSS", level: 80, icon: "SiTailwindcss" },
    { name: "Web Sockets", level: 80, icon: "SiSocketdotio" },
    { name: "Radix UI", level: 80, icon: "TbBrandRadixUi" },
  ],
};
